# Change these first
owner: CachyOS
repo: statuspage
assignees:
  - vnepogodin
  - ptr1337

sites:
  - name: Website
    url: https://cachyos.org/
  - name: Tebi CDN (USA, Germany, Singapore)
    url: https://cdn-1.cachyos.org/x86_64/cachyos/cachyos.db
  - name: CDN77 CDN (Worldwide Cache)
    url: https://cdn77.cachyos.org/repo/x86_64/cachyos/cachyos.db
  - name: DE mirror
    url: https://mirror.cachyos.org/
  - name: DE2 mirror
    url: https://aur.cachyos.org/
  - name: France mirror
    url: https://mirror.lesviallon.fr/cachy/
  - name: Russia mirror
    url: https://mirror.truenetwork.ru/cachy/
  - name: USA mirror
    url: https://us.cachyos.org/
  - name: Norway2 Mirror
    url: https://no.mirror.cx/cachyos/
  - name: Austria Mirror
    url: https://at.cachyos.org
    assignees:
      - SoulHarsh007
  - name: South Korea Mirror 2
    url: https://mirror.funami.tech/cachy/
  - name: China Mirror 20GBs
    url: https://mirrors.tuna.tsinghua.edu.cn/cachyos/

status-website:
  cname: status.cachyos.org
  logoUrl: https://github.com/CachyOS/website/raw/develop/src/assets/images/logo.svg
  name: CachyOS Status Page
  introTitle: "is CachyOS down?"
  introMessage: This is a status page of CachyOS servers hosted on GitHub
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Homepage
      href: https://cachyos.org/

# Configuration of the bots commits
commitMessages:
  commitAuthorName: "Cachy uptime-bot"
  commitAuthorEmail: "uptime-bot@cachyos.org"

# Recommended for GitHub API to work
user-agent: cachyos

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
