# Change these first
owner: CachyOS
repo: statuspage
assignees:
  - vnepogodin
  - ptr1337

sites:
  - name: Web Server
    url: https://cachyos.org/
  - name: Mirror
    url: https://mirror.cachyos.org/
  - name: Aur
    url: https://aur.cachyos.org/
  - name: Matrix Server
    url: https://matrix.cachyos.org/

status-website:
  cname: status.cachyos.org
  logoUrl: https://github.com/CachyOS/website/raw/develop/src/assets/images/logo.svg
  name: CachyOS Status Page
  introTitle: "cachyosisdown?"
  introMessage: This is a status page of CachyOS servers hosted on GitHub
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Homepage
      href: https://cachyos.org/

# Configuration of the bots commits
commitMessages:
  commitAuthorName: "Cachy uptime-bot"
  commitAuthorEmail: "uptime-bot@cachyos.org"

# Recommended for GitHub API to work
user-agent: cachyos

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
