# Change these first
owner: CachyOS
repo: statuspage
assignees:
  - vnepogodin
  - ptr1337

sites:
  - name: Website
    url: https://cachyos.org/
  - name: DE mirror
    url: https://mirror.cachyos.org/
  - name: DE2 mirror
    url: https://aur.cachyos.org/
  - name: Hungary mirror
    url: https://hun.cachyos.org/
  - name: France mirror
    url: https://mirror.lesviallon.fr/cachy/
  - name: Russia mirror
    url: https://mirror.truenetwork.ru/cachy/
  - name: South Korea mirror
    url: https://kr.cachyos.org/
    assignees:
      - silent-heigou
  - name: USA mirror
    url: https://us.cachyos.org/
  - name: CDN US/Global mirror
    url: https://us.soulharsh007.dev/repo/x86_64/cachyos/cachyos.db
    assignees:
      - SoulHarsh007
  - name: India mirror
    url: https://mirror.albony.xyz/cachylinux/
    assignees:
      - Albonycal
  - name: Matrix Server
    url: https://matrix.cachyos.org/

status-website:
  cname: status.cachyos.org
  logoUrl: https://github.com/CachyOS/website/raw/develop/src/assets/images/logo.svg
  name: CachyOS Status Page
  introTitle: "is CachyOS down?"
  introMessage: This is a status page of CachyOS servers hosted on GitHub
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Homepage
      href: https://cachyos.org/

# Configuration of the bots commits
commitMessages:
  commitAuthorName: "Cachy uptime-bot"
  commitAuthorEmail: "uptime-bot@cachyos.org"

# Recommended for GitHub API to work
user-agent: cachyos

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
